# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='Hora_fin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='Hora_inicio',
        ),
    ]
