# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 12:16
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20171116_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='banner',
            field=models.ImageField(default=b'static/eventos/dist/img/avatar.png', storage=django.core.files.storage.FileSystemStorage(location=b'eventos/static/eventos/dist/img/imgnews/'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
