# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20171211_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='celular',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='direccion_inscrito',
            field=models.CharField(default=b'Sin Direccion', max_length=100),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nombre_inscrito',
            field=models.CharField(default=b'N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='inscrito',
            field=models.BigIntegerField(),
        ),
    ]
