# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20171214_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor_inscripcion',
            field=models.BigIntegerField(default=0),
        ),
    ]
