# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_inscripcion_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='sexo',
            field=models.CharField(default=b'N', max_length=10),
        ),
    ]
